name: runvibe_mobile
description: Aplicativo mobile de corrida RunVibe.
publish_to: none
version: 1.3.0+6

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  equatable: ^2.0.7
  get_it: ^8.2.0
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  location: ^10.0.1
  flutter_foreground_task: ^10.0.0
  maplibre_gl: ^0.26.2
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^17.3.0
  flutter_secure_storage: ^10.3.1
  connectivity_plus: ^7.0.0
  uuid: ^4.5.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
